import type { Metadata } from "next";
import { Montserrat_Alternates } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Custom Grown Font


const gloock = localFont({
  src: '/fonts/Gloock-Regular.ttf',
  display: 'swap',
  weight: '400',
  style: 'normal',
  variable: '--font-Gloock',
});

// Montserrat Alternates from Google Fonts
const montserratAlternates = Montserrat_Alternates({
  subsets: ['latin'],
  weight: ['400'],
  style: ['normal'],
  variable: '--font-Montserrat',
  display: 'swap',
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`  ${montserratAlternates.variable} $ ${gloock.variable}`}>
      <body>
        <div>
          {children}
        </div>
      </body>
    </html>
  );
}